apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meal-planner
  name: app-service
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    spec:
      $setElementOrder/containers:
        - name: app-service
      containers:
        - name: app-service
          imagePullPolicy: IfNotPresent
          env:
            # Let NGinX Proxy's LetsEncrypt companion to handle the SSL certificate
            - name: LETSENCRYPT_HOST
              value: ${LETSENCRYPT_HOST}
            - name: LETSENCRYPT_EMAIL
              value: ${LETSENCRYPT_EMAIL}
      imagePullSecrets:
        - name: regcred # Required for self hosted registry
