apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: app-service
      containers:
        - name: app-service
          imagePullPolicy: IfNotPresent
          env:
            # Let NGinX Proxy's LetsEncrypt companion to handle the SSL certificate
            - name: LETSENCRYPT_HOST
              value: ${LETSENCRYPT_HOST}
            - name: LETSENCRYPT_EMAIL
              value: ${LETSENCRYPT_EMAIL}
      imagePullSecrets:
        - name: regcred # Required for self hosted registry
