apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
  - name: app-service
    newName: localhost:5000/meal-planner/app-service
    newTag: 0.4.0
  - name: shopping-list-service
    newName: localhost:5000/meal-planner/shopping-list-service
    newTag: 0.2.0
