apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  # Microservices
  - ./app.yml
  - ./shoppingList.yml

images:
  - name: app-service
    newName: registry.nerdieworks.nl/meal-planner/app-service
    newTag: 0.6.0
  - name: shopping-list-service
    newName: registry.nerdieworks.nl/meal-planner/shopping-list-service
    newTag: 0.4.0
