apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-service
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: shopping-list-service
      containers:
        - name: shopping-list-service
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred # Required for self hosted registry
