apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meal-planner
  name: app-service
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    spec:
      $setElementOrder/containers:
        - name: app-service
      containers:
        - name: app-service
          imagePullPolicy: IfNotPresent
          env:
            # Configure letsencrypt-nginx-proxy-companion
            - name: LETSENCRYPT_HOST
              valueFrom:
                secretKeyRef:
                  name: letsencrypt
                  key: host
            - name: LETSENCRYPT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: letsencrypt
                  key: email
      imagePullSecrets:
        - name: regcred # Required for self hosted registry
