apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Prerequisites
  - namespace.yml
  - networking/istio.generated.yml

  # Third party services
  - persistance/eventStore.yml

  # Microservices
  - services/app.yml
  - services/shoppingList.yml

  # Istio
  - networking/destinationRules.yml
  - networking/gateway.yml
