apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Prerequisites
  - namespace.yml
  - istio.generated.yml

  # Third party services
  - eventStore.yml

  # Microservices
  - app.yml
  - shoppingList.yml

  # Istio
  - destinationRules.yml
  - gateway.yml
