apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meal-planner
  name: shopping-list-service
  labels:
    app: shopping-list
    version: v1
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: shopping-list
      version: v1
  template:
    metadata:
      labels:
        app: shopping-list
        version: v1
    spec:
      # @todo Add service account
      # @todo Add imagePullPolicy: IfNotPresent and override to Always for development
      containers:
        - image: shopping-list-service
          # @todo Add imagePullPolicy: IfNotPresent and override to Never for development
          imagePullPolicy: Never
          name: shopping-list-service
          resources: {}
          ports:
            - containerPort: 3000
status: {}

---
apiVersion: v1
kind: Service
metadata:
  namespace: meal-planner
  name: shopping-list-service
  labels:
    app: shopping-list
    service: shopping-list
spec:
  selector:
    app: shopping-list
  ports:
    - name: http
      protocol: TCP
      port: 3000
