apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  # Microservices
  - ./app.yml
  - ./shoppingList.yml

images:
  - name: app-service
    newName: ${DOCKER_REGISTRY}app-service
    newTag: 0.7.0
  - name: shopping-list-service
    newName: ${DOCKER_REGISTRY}shopping-list-service
    newTag: 0.6.1
