apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - configs/registry.yml
  - configs/letsencrypt.yml

patchesStrategicMerge:
  # Services
  - services/app.yml
  - services/list.yml

images:
  - name: app-service
    newName: ${DOCKER_REGISTRY}app-service
    newTag: 0.13.0
  - name: list-service
    newName: ${DOCKER_REGISTRY}list-service
    newTag: 0.11.0
