apiVersion: v1
kind: Secret
metadata:
  namespace: meal-planner
  name: auth0
data:
  domain: "${AUTH0_DOMAIN_BASE64}"
  clientId: "${AUTH0_CLIENT_ID_BASE64}"
  clientSecret: "${AUTH0_CLIENT_SECRET_BASE64}"
  audience: "${AUTH0_AUDIENCE_BASE64}"
  cookieSecret: "${AUTH0_COOKIE_SECRET_BASE64}"
  # See RequestAuthentication in services
  # jwtIssuer: "https://${AUTH0_DOMAIN}/"
  # jwtJwksUri: "https://$(AUTH0_DOMAIN)/.well-known/jwks.json"
