apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meal-planner
  name: app-service
  creationTimestamp: null
  labels:
    service: app
    app: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: app
    spec:
      containers:
        - image: app-service
          name: app-service
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: LETSENCRYPT_HOST
              value: boodschappen.nerdieworks.nl
            - name: LETSENCRYPT_EMAIL
              value: maurits@nerdieworks.nl
status: {}

---
apiVersion: v1
kind: Service
metadata:
  namespace: meal-planner
  name: app-service
spec:
  selector:
    service: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
