apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Prerequisites
  - namespace.yml

  # Third party services
  - eventStore.yml

  # Microservices
  - app.yml
  - shoppingList.yml
