apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  # Services
  - services/app.yml

images:
  - name: app-service
    newTag: latest
  - name: list-service
    newTag: latest
