name: Deploy infrastructure on commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Kubectl
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_BASE64 }}
        run: echo "$KUBE_CONFIG_DATA" | base64 --decode > ./kubeconfig

      - name: Install and verify Istio
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          ISTIO_VERSION: 1.6.0
        run: |
          echo "=> Set Kubectl configuration"
          mkdir ~/.kube && cp ./kubeconfig ~/.kube/config

          echo "=> Install Istioctl"
          curl -L https://istio.io/downloadIstio | sh -
          export PATH="$PATH:istio-${ISTIO_VERSION}/bin"

          echo "=> Install Istio"
          istioctl install -f istio/profile.yml --skip-confirmation

          echo "=> Verify Istio"
          istioctl verify-install -f ./kubernetes/base/networking/istio.generated.yml
          istioctl analyze

      - name: Build Kubernetes manifest
        uses: stefanprodan/kube-tools@v1
        with:
          # @todo Configure explicit versions for stefanprodan/kube-tools@v1 uses
          # kubectl: 1.18.0
          # kustomize: 3.4.0
          # helm: 2.16.5
          # helmv3: 3.1.2
          command: kustomize build ./kubernetes/production/ > ./manifest.template.yml

      # Using environment variables is not yet supported by Kustomize, so use envsubst instead.
      # See https://github.com/kubernetes-sigs/kustomize/issues/388
      - name: Replace environment variables in Kubernetes manifest
        uses: nowactions/envsubst@v1
        env:
          HOST_DOMAIN: ${{ secrets.HOST_DOMAIN }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

          # Configure letsencrypt-nginx-proxy-companion (optional)
          # See https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion
          LETSENCRYPT_HOST: ${{ secrets.LETSENCRYPT_HOST }}
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}

          # Configure Auth0
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_DOMAIN_BASE64: ${{ secrets.AUTH0_DOMAIN_BASE64 }}
          AUTH0_CLIENT_ID_BASE64: ${{ secrets.AUTH0_CLIENT_ID_BASE64 }}
          AUTH0_CLIENT_SECRET_BASE64: ${{ secrets.AUTH0_CLIENT_SECRET_BASE64 }}
          AUTH0_COOKIE_SECRET_BASE64: ${{ secrets.AUTH0_COOKIE_SECRET_BASE64 }}

        with:
          input: ./manifest.template.yml
          output: ./manifest.yml

      - name: Apply manifest to Kubernetes cluster
        uses: stefanprodan/kube-tools@v1
        with:
          command: kubectl apply --kubeconfig=./kubeconfig -f ./manifest.yml
      # Don't upload manifest as long as it can contain secrets
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: manifest.yml
      #     path: ./manifest.template.yml
