name: Deploy infrastructure on commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: stefanprodan/kube-tools@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          # @todo Configure explicit versions
          # kubectl: 1.18.0
          # kustomize: 3.4.0
          # helm: 2.16.5
          # helmv3: 3.1.2
          command: |
            # Fail on non-zero exit code
            set -e

            echo "Authenticate"
            echo "$KUBE_CONFIG_DATA" | base64 --decode > /tmp/kubeconfig

            echo "Build Kubernetes configuration"
            kustomize build production/ > /tmp/manifest.yml

            echo "Deploy to TransIP VPS"
            kubectl apply --insecure-skip-tls-verify --kubeconfig=/tmp/kubeconfig -f /tmp/manifest.yml
