name: Deploy infrastructure on commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Kubernetes manifest
        uses: stefanprodan/kube-tools@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          # @todo Configure explicit versions
          # kubectl: 1.18.0
          # kustomize: 3.4.0
          # helm: 2.16.5
          # helmv3: 3.1.2
          command: |
            # Fail on non-zero exit code
            set -e

            echo "Authenticate"
            echo "$KUBE_CONFIG_DATA" | base64 --decode > ./kubeconfig

            echo "Build Kubernetes configuration"
            # Environment variable substitution is not supported by Kustomize yet,
            # so use envsubst instead.
            # See https://github.com/kubernetes-sigs/kustomize/issues/388
            kustomize build production/ > ./manifest.template.yml

      - name: Replace environment variables
        uses: nowactions/envsubst@v1
        env:
          # Add the LETSENCRYPT_HOST and LETSENCRYPT_EMAIL secrets
          # if you are using the letsencrypt-nginx-proxy-companion.
          # See https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion
          LETSENCRYPT_HOST: ${{ secrets.LETSENCRYPT_HOST }}
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        with:
          input: ./manifest.template.yml
          output: ./manifest.yml

      - name: Deploy to VPS
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            # Fail on non-zero exit code
            set -e

            echo "Deploy to TransIP VPS"
            kubectl apply --insecure-skip-tls-verify --kubeconfig=./kubeconfig -f ./manifest.yml

      - uses: actions/upload-artifact@v2
        with:
          name: manifest.yml
          path: ./manifest.template.yml
