name: Deploy infrastructure on commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Kubernetes manifest
        uses: stefanprodan/kube-tools@v1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          # @todo Configure explicit versions
          # kubectl: 1.18.0
          # kustomize: 3.4.0
          # helm: 2.16.5
          # helmv3: 3.1.2
          command: |
            # Fail on non-zero exit code
            set -e

            echo "Authenticate"
            echo "$KUBE_CONFIG_DATA" | base64 --decode > /tmp/kubeconfig

            echo "Build Kubernetes configuration"
            # Environment variable substitution is not supported by Kustomize yet,
            # so use envsubst instead.
            # See https://github.com/kubernetes-sigs/kustomize/issues/388
            kustomize build production/ > /tmp/manifest.template.yml

      - name: Replace environment variables
        uses: nowactions/envsubst@v1
        env:
          LETSENCRYPT_HOST: ${{ secrets.LETSENCRYPT_HOST }}
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        with:
          input: /tmp/manifest.template.yml
          output: /tmp/manifest.yml

      - name: Deploy to VPS
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            # Fail on non-zero exit code
            set -e

            echo "Deploy to TransIP VPS"
            kubectl apply --insecure-skip-tls-verify --kubeconfig=/tmp/kubeconfig -f /tmp/manifest.yml
